version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5734
      POSTGRES_DB: freelancer
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:5734@postgres:5432/freelancer
    ports:
      - '3000:3000'

volumes:
  pgdata:
